### ISSUE TITLE
Compress uploaded images

### ISSUE THREAD

**Issue by Prydeton** [stevent-team/stevent#51]
Profile images, event banners and club icons should be compressed when uploaded and potentially converted to jpg (extra compression), although that would remove transparency. Maybe we can convert all transparency to white when converting to jpg.

**Comment by GRA0007** [comment]
I think we should also look into compressing uploaded images as well, and converting to jpg

**Comment by giraugh** [comment]
> Images currently also are missing file extensions after being uploaded
