### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by Prydeton** [stevent-team/stevent#70]
Oooh yeah, so here's my outline for how this is going to work.

We're going to be basing this off how Google Calendar handles recurring events, so, when an event is created, a user can mark it as a recurring event. They can choose:

- weekly (and select which days of the week it occurs on)
- monthly

And then they must also specify either how many events to be included, _or_, a date on which the recurrences will stop.

When clicking `create`, the backend will take the recurrence parameters and create separate events for every recurrence. These will all be tied together with a single event ID however.

The event feed will check for the `recurring` field on an event and if contains an ID, only show the soonest upcoming event from that series. Everywhere else, these events will show up separately (i.e. on the profile page and club page) All recurrences will however have a badge that identifies them as recurring events, ideally with some human-readable interval, such as "every Wednesday" or "monthly on the 15th".

On the event details page, if it's a recurring event, there will be a section to show that and it will include a list of all the other recurrences of that series.

When editing or deleting a recurring event, the user will be asked if they would like to edit/delete just that single event or edit/delete all recurrences of that event. Note, if a single event is edited, and then later _all_ recurrences are edited, that action will overwrite any changes done to that single event, i.e. events continue to be linked together even when edited or single events are deleted. This means, unlike Google calendar, once a recurring event is created, it's recurrence rules can't be updated for events that have already happened in the past. Updating these will only adjust future occurrences in that series.

Finally, there is a limit of 30 occurrences when creating a recurring event. If the user wishes to make more, then they must create a separate event. This prevents abuse of the system or mistakes causing damage.

Note: #103 will need to be completed before this can be implemented on the front end

**Comment by GRA0007** [comment]
Would be good to have a checkbox when creating for a recurring event, then a dropdown for: weekly, monthly, and an end date. This would then display as "sub-events", so would technically make just one event, but when clicking on it would show each event and whether you are attending each one or not.
In the event feed, the repeating event would only display once, still more to be figured out about this and how it displays across the site

**Comment by GRA0007** [comment]
Leaving this here for reference
![image](https://user-images.githubusercontent.com/8862273/127656070-90c9bb0c-14a9-4d30-af2b-cd32172bd62d.png)
![image](https://user-images.githubusercontent.com/8862273/127656154-b5377d48-c1c6-4482-8878-9a1c5f7fc03f.png)
