### ISSUE TITLE
Subscribed and Upcoming filters are mutually exclusive

### ISSUE THREAD

**Issue by giraugh** [stevent-team/stevent#90]
Would be nice to be able to filter for 'upcoming subscribed' events.

**Comment by GRA0007** [comment]
This can be implemented along with #57, as there will be no way of viewing all previous events from the feed anymore

**Comment by GRA0007** [comment]
I'm going to close this for now, since the "subscribed" filter now only fetched upcoming events. We can reopen this if we think there's a need for "subscribed, past event", which I don't think will be necessary, since you'll be able to see all club events on the club pages soon.
